{% set version = "1.9.0" %}


package:
  name: hpx
  version: {{ version }}

source:
  url: https://github.com/STEllAR-GROUP/hpx/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 328766a059e2ab5b9666793b3d8a1c65b72a8d380a8ac7921271c8646996034b
  patches:
    - patch/hpx-{{ version }}.patch

build:
  number: 0

requirements:
  build:
    # Section for the native build platform. Think "build-tools", that run on the native platform,
    # but output results for the target platform.
    # Dependencies required during the build phase not needed on the host.
    - {{ compiler('cxx') }}
    - cmake
    - git                                        # [win]
    - ninja                                      # [not win]
  host:
    # Section for the target platform. Might not be the same as the build platform!
    # Dependencies required during build phase needed on the host.
    - asio
    - boost-cpp
    - gperftools                                 # [not win]
    - libhwloc
    - mimalloc                                   # [win]
  run:
    # Dependencies required for using the software.
    # Stuff required when building software that depends on HPX.
    - asio
    - boost-cpp
    - gperftools                                 # [not win]
    - mimalloc                                   # [win]

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja                                      # [not win]
  files:
    - test/CMakeLists.txt
    - test/hello_hpx.cpp

about:
  home: https://github.com/STEllAR-GROUP/hpx
  summary: The C++ Standard Library for Parallelism and Concurrency
  description: |
    HPX is a C++ Standard Library for Concurrency and Parallelism. It implements all of the
    corresponding facilities as defined by the C++ Standard. Additionally, in HPX we implement
    functionalities proposed as part of the ongoing C++ standardization process. We also extend
    the C++ Standard APIs to the distributed case.
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  doc_url: https://hpx.stellar-group.org/documentation
  dev_url: https://github.com/STEllAR-GROUP/hpx

extra:
  recipe-maintainers:
    - kordejong
    - oliverschmitz
    - hkaiser
